# Site settings

baseURL = ""
relativeurls = true
uglyurls = true
languageCode = "en-US"
title = "Microsoft Azure"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Copyright
copyright = "&copy;2021 Yingting Huang - Static Website for Demo Purpose"

[params]

  # Metadata for search engines and social sharing
  author = "Yingting Huang"
  description = "Sample static website for demo purpose."

  # Favicon
  favicon = "favicon.ico"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/regions.svg"
      position = "center center"

  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Connect"

      [[params.links.list1.link]]
        text = "Blog"
        url = "#"

      [[params.links.list1.link]]
        text = "Email"
        url = "#"

      [[params.links.list1.link]]
        text = "Newsletter"
        url = "#"

  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Social"

      [[params.links.list2.link]]
        text = "Twitter"
        url = "#"

      [[params.links.list2.link]]
        text = "Instagram"
        url = "#"

      [[params.links.list2.link]]
        text = "Dribbble"
        url = "#"
